{{- $global := .Values.global | default dict }}
{{- range $index, $machine := .Values.machines }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: {{ include "cluster.name" $ }}-{{ $index }}
spec:
  clusterName: {{ include "cluster.name" $ }}
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: {{ include "cluster.name" $ }}-{{ $index }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: {{ include "cluster.name" $ }}-{{ $index }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: {{ include "cluster.name" $ }}-{{ $index }}
  annotations:
    # Temporary fix to address https://github.com/k0sproject/k0smotron/issues/942
    # to prevent premature K0sWorkerConfig deletion
    helm.sh/resource-policy: keep
spec:
  version: {{ $.Values.k0s.version }}
  {{- if $global.k0sURL }}
  downloadURL: "{{ $global.k0sURL }}/k0s-{{ $.Values.k0s.version }}-{{ $.Values.k0s.arch }}"
  {{- end }}
  {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
  {{- $certs := dict "registry.crt" $global.registryCertSecret "k0s-url.crt" $global.k0sURLCertSecret }}
  files:
    {{- range $path, $secret := $certs }}
    {{- if $secret }}
    - contentFrom:
        secretRef:
          name: {{ $secret }}
          key: ca.crt
      permissions: "0664"
      path: /usr/local/share/ca-certificates/{{ $path }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if or $.Values.machinePreStartCommands $global.registryCertSecret $global.k0sURLCertSecret }}
  preStartCommands:
    {{- range $.Values.machinePreStartCommands }}
    - {{ printf "%s%s" (ternary "sudo " "" ($machine.useSudo | default false)) . | quote }}
    {{- end }}
    {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
    - {{ printf "%supdate-ca-certificates" (ternary "sudo " "" ($machine.useSudo | default false)) | quote }}
    {{- end }}
  {{- end }}
  {{- if and $machine.k0s $machine.k0s.args }}
  args:
    {{- toYaml $machine.k0s.args | nindent 4 }}
  {{- end }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: {{ include "cluster.name" $ }}-{{ $index }}
spec:
  address: {{ $machine.address }}
  {{- if $machine.port }}
  port: {{ $machine.port }}
  {{- end }}
  {{- if $machine.user }}
  user: {{ $machine.user }}
  {{- end }}
  {{- if $machine.useSudo }}
  useSudo: {{ $machine.useSudo }}
  {{- end }}
  {{- with $machine.provisionJob }}
  provisionJob:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  sshKeyRef:
    name: {{ $.Values.clusterIdentity.name }}
  customCleanUpCommands:
    - "/usr/local/bin/k0s etcd leave"
    - "/usr/local/bin/k0s stop"
    - "/usr/local/bin/k0s reset"
    - "rm /usr/local/bin/k0s"
    - "rm /usr/local/bin/k0s-worker-wrapper.sh"
    - "netbird deregister"
    - "apt-get remove -y netbird"
---
{{- end }}
